text1 = 'welcome To the  Armenian /Year 2022/'
# print(text1.capitalize())
# print(text1.casefold())
# print(text1.center(55))
# # ?
# print(text1.count('2'))
# print(text1.encode())
# # ?
# print(text1.endswith('2'))
# print(text1.expandtabs(1))
# # ?
print(text1.find('T'))
print(text1.format(price=52))
# print(text1.format_map())
print(text1.index('c'))
print(text1.isalnum())
print(text1.isalpha())
# ?chhaskaca erba true linum
print(text1.isascii())
print(text1.isdecimal())
print(text1.isdigit())
print(text1.isidentifier())
print(text1.islower())
print(text1.isnumeric())
print(text1.isprintable())
print(text1.isspace())
print(text1.istitle())
print(text1.isupper())
print(text1.join('Wel'))
print(text1.ljust(0))
print(text1.lower())
print(text1.lstrip())
z = (text1.maketrans('T', 'D'))
print(text1.translate(z))
print(text1.partition("The"))
print(text1.replace('Armenia', 'Canada'))
print(text1.rfind('a'))
print(text1.rindex('a'))
# naxord 2-i tarberutyun
print(text1.rjust(10))
print(text1.rpartition('T'))
print(text1.rsplit())
print(text1.rstrip())
print(text1.split('o'))
print(text1.splitlines())
print(text1.strip('W'))
print(text1.startswith('W'))
print(text1.swapcase())
print(text1.title())
print(text1.upper())
print(text1.zfill(37))
print(len(text1))